version: "3"
services:
  php-fpm:
    build:
      context: ./docker/php-fpm
      args:
        - TZ=${TZ}
    volumes:
      - ./src:/var/www/html
      - ./logs:/var/log/php-fpm
      - ./docker/php-fpm/php.ini:/usr/local/etc/php-fpm/php.ini
    working_dir: /var/www/html
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=mysql
      - DB_DATABASE=${DB_NAME}
      - DB_USERNAME=${DB_USER}
      - DB_PASSWORD=${DB_PASS}
      - TZ=${TZ}
  nginx:
    build:
      context: ./docker/nginx
    depends_on:
      - php-fpm
    ports:
      - 8080:80
    volumes:
      - ./src:/var/www/html
      - ./logs:/var/log/nginx
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    environment:
      - TZ=${TZ}
  mysql:
    build:
      context: ./docker/mysql
    ports:
      - 33060:3306
    volumes:
      - db-store:/var/lib/mysql
      - ./logs:/var/log/mysql
      - ./docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
    environment:
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASS}
      - MYSQL_ROOT_PASSWORD=${DB_PASS}
      - TZ=${TZ}
volumes:
  db-store:

