version: "3"
services:
  app: #アプリケーションサーバ
    build:
      context: ./docker/php # Dockerfileのある場所を指定する
      args: # build時のオプション
        - TZ=${TZ} # Dockerfileで使用
    volumes:
        - ./src:/work
        - ./logs:/var/log/app
        - ./docker/php/php.ini:/usr/local/etc/php/php.ini
    working_dir: /work
    environment: # 環境変数を追加
        - DB_CONNECTION=mysql # DB_*はlaravel用の環境変数
        - DB_HOST=db
        - DB_DATABASE=${DB_NAME}
        - DB_USERNAME=${DB_USER}
        - DB_PASSWORD=${DB_PASS}
        - TZ=${TZ} # php.iniで使用
  web: #Webサーバ
    image: nginx:1.17-alpine
    depends_on:
      - app
    ports:
      - 20080:80
    volumes:
      - ./src:/work
      - ./logs:/var/log/nginx
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    environment:
      - TZ=${TZ}
  db: #データベース
    image: mysql:5.7
    ports:
      - 23306:3306
    volumes:
      - db-store:/var/lib/mysql
      - ./logs:/var/log/mysql
      - ./docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
    environment:
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASS}
      - MYSQL_ROOT_PASSWORD=${DB_PASS}
      - TZ=${TZ}
volumes:
  db-store:
