version: "3"
services:
  laravel_app:
    build:
      context: ./docker/php # Dockerfileのある場所を指定する
      args: # build時のオプション
        - TZ=${TZ} # Dockerfileで使用
    volumes:
        - ./src:/work
        - ./logs:/var/log/app
        - ./docker/php/php.ini:/usr/local/etc/php/php.ini
    working_dir: /work
    environment: # 環境変数を追加
        - DB_CONNECTION=mysql # DB_*はlaravel用の環境変数
        - DB_HOST=db
        - DB_DATABASE=${DB_NAME}
        - DB_USERNAME=${DB_USER}
        - DB_PASSWORD=${DB_PASS}
        - TZ=${TZ} # php.iniで使用